services:
  purr-api:
    image: ghcr.io/theahadev/purrcrypt-api:latest
    container_name: purrcrypt-api
    restart: unless-stopped
    ports:
      - "5000:5000"

  purr-web:
    image: sigoden/dufs:latest
    container_name: purrcrypt-webui
    restart: unless-stopped
    user: "1000:1000"
    ports:
      - "4000:4000"
    volumes:
      - ./webui:/data:ro
    command: >
      /data
      --bind 0.0.0.0
      --port 4000
      --enable-cors
      --render-index
      --render-spa
